//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number should not be more than 20 characters.
        /// </summary>
        public static string AccountNumber_Length {
            get {
                return ResourceManager.GetString("AccountNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Account Number.
        /// </summary>
        public static string AccountNumber_Pattern {
            get {
                return ResourceManager.GetString("AccountNumber_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number is required.
        /// </summary>
        public static string AccountNumber_Required {
            get {
                return ResourceManager.GetString("AccountNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving document ! Please contact administrator..
        /// </summary>
        public static string BadRequestErrorMessage {
            get {
                return ResourceManager.GetString("BadRequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document File should be less than 16 MB.
        /// </summary>
        public static string DocumentImage_Size {
            get {
                return ResourceManager.GetString("DocumentImage_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name should not be more than 100 characters.
        /// </summary>
        public static string DocumentName_Length {
            get {
                return ResourceManager.GetString("DocumentName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Document Name.
        /// </summary>
        public static string DocumentName_Pattern {
            get {
                return ResourceManager.GetString("DocumentName_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name is required.
        /// </summary>
        public static string DocumentName_Required {
            get {
                return ResourceManager.GetString("DocumentName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Document..
        /// </summary>
        public static string DocumentServiceFailureMessage {
            get {
                return ResourceManager.GetString("DocumentServiceFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string DocumentServiceSuccessMessage {
            get {
                return ResourceManager.GetString("DocumentServiceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Document Type.
        /// </summary>
        public static string DocumentType_Pattern {
            get {
                return ResourceManager.GetString("DocumentType_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type is required.
        /// </summary>
        public static string DocumentType_Required {
            get {
                return ResourceManager.GetString("DocumentType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type should not be more than 50 characters.
        /// </summary>
        public static string DocumenType_Length {
            get {
                return ResourceManager.GetString("DocumenType_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        public static string EmptyMetadataMessage {
            get {
                return ResourceManager.GetString("EmptyMetadataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving the data.
        /// </summary>
        public static string Exception_Error_Message {
            get {
                return ResourceManager.GetString("Exception_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Clinical Document API.
        /// </summary>
        public static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Code must be 4 characters only.
        /// </summary>
        public static string FacilityCode_Length {
            get {
                return ResourceManager.GetString("FacilityCode_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Facility Code.
        /// </summary>
        public static string FacilityCode_Pattern {
            get {
                return ResourceManager.GetString("FacilityCode_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Code is required.
        /// </summary>
        public static string FacilityCode_Required {
            get {
                return ResourceManager.GetString("FacilityCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured ! Please contact administrator..
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context is null..
        /// </summary>
        public static string InvalidContextMessage {
            get {
                return ResourceManager.GetString("InvalidContextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mime Type not be more than 100 chanracters.
        /// </summary>
        public static string MimeType_Length {
            get {
                return ResourceManager.GetString("MimeType_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source System not be more than 20 chanracters.
        /// </summary>
        public static string SourceSystem_Length {
            get {
                return ResourceManager.GetString("SourceSystem_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record : {0} saved successfully..
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records found..
        /// </summary>
        public static string ValidMetadataMessage {
            get {
                return ResourceManager.GetString("ValidMetadataMessage", resourceCulture);
            }
        }
    }
}
