// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Test.R1.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SaveClinicalDocumentFeature : object, Xunit.IClassFixture<SaveClinicalDocumentFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public SaveClinicalDocumentFeature(SaveClinicalDocumentFeature.FixtureData fixtureData, Test_R1_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SaveClinicalDocument", "\tIn order to save patients document\r\n\tAs a R1 Chart Master\r\n\tI want to consume pa" +
                    "tients document details in specific JSON format", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="To Save Clinical Document Details")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "To Save Clinical Document Details")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ToSaveClinicalDocumentDetails()
        {
            string[] tagsOfScenario = new string[] {
                    "SaveClinicalDocumentDetails"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Save Clinical Document Details", null, new string[] {
                        "SaveClinicalDocumentDetails"});
            this.ScenarioInitialize(scenarioInfo);
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("I have received Patients Clinical Document Details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.When("I consume JSON and make API call", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then("the result should be saved in database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.And("We receive response message in response body", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            this.ScenarioCleanup();
        }
        
        public virtual void ValidationsInRequestJSON(string parameter, string value, string code, string responseMessage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SaveClinicalDocumentDetails"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validations in request JSON", null, @__tags);
            this.ScenarioInitialize(scenarioInfo);
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given(string.Format("I have request JSON for saving clinical documents with \"{0}\" \"{1}\"", parameter, value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.When("I call the API service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then(string.Format("user receive HTTP response {0}", code), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.And(string.Format("\"{0}\" in response body", responseMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON: AccountNumber")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON: AccountNumber")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSON_AccountNumber()
        {
            this.ValidationsInRequestJSON("AccountNumber", "", "400", "Account Number is required", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON: FacilityCode")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON: FacilityCode")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSON_FacilityCode()
        {
            this.ValidationsInRequestJSON("FacilityCode", "", "400", "Facility Code is required", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON: DocumentType")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON: DocumentType")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSON_DocumentType()
        {
            this.ValidationsInRequestJSON("DocumentType", "", "400", "Document Type is required", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON: DocumentName")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON: DocumentName")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSON_DocumentName()
        {
            this.ValidationsInRequestJSON("DocumentName", "", "400", "Document Name is required", ((string[])(null)));
        }
        
        public virtual void ValidationsInRequestJSONWithInvalidInputs(string parameter, string value, string code, string responseMessage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SaveClinicalDocumentDetails"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validations in request JSON with invalid inputs", null, @__tags);
            this.ScenarioInitialize(scenarioInfo);
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given(string.Format("I have request JSON for saving clinical documents in API with \"{0}\" \"{1}\"", parameter, value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.When("I call the Clinical Document API service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then(string.Format("user receives the HTTP response {0}", code), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.And(string.Format("\"{0}\" in the response body", responseMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON with invalid inputs: Variant 0")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON with invalid inputs: Variant 0")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSONWithInvalidInputs_Variant0()
        {
            this.ValidationsInRequestJSONWithInvalidInputs("AccountNumber", "!@#", "400", "Please enter valid Account Number", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON with invalid inputs: Variant 1")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON with invalid inputs: Variant 1")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSONWithInvalidInputs_Variant1()
        {
            this.ValidationsInRequestJSONWithInvalidInputs("FacilityCode", "!@#!", "400", "Please enter valid Facility Code", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON with invalid inputs: Variant 2")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON with invalid inputs: Variant 2")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSONWithInvalidInputs_Variant2()
        {
            this.ValidationsInRequestJSONWithInvalidInputs("DocumentType", "!@#", "400", "Please enter valid Document Type", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON with invalid inputs: Variant 3")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON with invalid inputs: Variant 3")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSONWithInvalidInputs_Variant3()
        {
            this.ValidationsInRequestJSONWithInvalidInputs("DocumentType", "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcda" +
                    "bcdabcdabcdabcdabcdabcd", "400", "Document Type should not be more than 50 characters", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON with invalid inputs: Variant 4")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON with invalid inputs: Variant 4")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSONWithInvalidInputs_Variant4()
        {
            this.ValidationsInRequestJSONWithInvalidInputs("DocumentName", "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcda" +
                    "bcdabcdabcdabcdabcdabcd", "400", "Document Name should not be more than 100 characters", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON with invalid inputs: Variant 5")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON with invalid inputs: Variant 5")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSONWithInvalidInputs_Variant5()
        {
            this.ValidationsInRequestJSONWithInvalidInputs("AccountNumber", "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcda" +
                    "bcdabcdabcdabcdabcdabcd", "400", "Account Number should not be more than 20 characters", ((string[])(null)));
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validations in request JSON with invalid inputs: Variant 6")]
        [Xunit.TraitAttribute("FeatureTitle", "SaveClinicalDocument")]
        [Xunit.TraitAttribute("Description", "Validations in request JSON with invalid inputs: Variant 6")]
        [Xunit.TraitAttribute("Category", "SaveClinicalDocumentDetails")]
        public virtual void ValidationsInRequestJSONWithInvalidInputs_Variant6()
        {
            this.ValidationsInRequestJSONWithInvalidInputs("FacilityCode", "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcda" +
                    "bcdabcdabcdabcdabcdabcd", "400", "Facility Code must be 4 characters only", ((string[])(null)));
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SaveClinicalDocumentFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SaveClinicalDocumentFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
